### ISSUE TITLE
repo doesnt contain node_modules

### ISSUE THREAD

**Issue by HarryMcCarney** [CompositionalIT/simple-fable#1]
so example from documentation wont run node_modules\.bin\webpack-dev-server

node_modules is included in [simple-safe](https://github.com/CompositionalIT/simple-safe)

**Comment by isaacabraham** [comment]
I've updated the instructions: You need to run `npm install` first to bring down the NPM modules, and `dotnet build` to build the source code. Only then can you run webpack.
